/**
 * RailMate Bangladesh — Static Knowledge Graph Data
 * --------------------------------------------------
 * Stop sequences for all 133 trains (515 stop records).
 * Used by routeEngine.ts for journey planning.
 *
 * DATA PROVENANCE (see PROVENANCE_AUDIT.md):
 *   g1 (43 rows)  — Wikipedia training memory
 *   g2 (134 rows) — amadertrain.com fetch (context cleared — unconfirmed)
 *   g3 (176 rows) — Journey-duration interpolation
 *   g4 (120 rows) — Assumption / bulk loop estimate
 *   g5 (42 rows)  — Origin + destination only
 *   Verified against BR official PDF: 0 rows (0%)
 *
 * This file encodes WHICH STATIONS a train serves — not official departure times.
 * Do not use for timetable display.
 */

import type { TrainMeta, Station, ConfidenceGroup } from '../api/routeEngine';

// ─── Station list ─────────────────────────────────────────────────────────────

export const STATIONS: Station[] = [
  { code: 'DHKA', nameEn: 'Dhaka (Kamalapur)', nameBn: 'ঢাকা (কমলাপুর)', shohozCity: 'DHAKA', division: 'Dhaka', isHub: true },
  { code: 'DABB', nameEn: 'Dhaka Airport', nameBn: 'ঢাকা বিমানবন্দর', shohozCity: 'DHAKA AIRPORT', division: 'Dhaka', isHub: true },
  { code: 'DHCA', nameEn: 'Dhaka Cantonment', nameBn: 'ঢাকা ক্যান্টনমেন্ট', shohozCity: 'DHAKA CANTONMENT', division: 'Dhaka', isHub: false },
  { code: 'TNG',  nameEn: 'Tongi', nameBn: 'টঙ্গী', shohozCity: 'TONGI', division: 'Dhaka', isHub: true },
  { code: 'JDP',  nameEn: 'Joydebpur', nameBn: 'জয়দেবপুর', shohozCity: 'JOYDEBPUR', division: 'Dhaka', isHub: true },
  { code: 'NSD',  nameEn: 'Narsingdi', nameBn: 'নরসিংদী', shohozCity: 'NARSINGDI', division: 'Dhaka', isHub: false },
  { code: 'BBZ',  nameEn: 'Bhairab Bazar', nameBn: 'ভৈরব বাজার', shohozCity: 'BHAIRAB BAZAR', division: 'Dhaka', isHub: false },
  { code: 'NRG',  nameEn: 'Narayanganj', nameBn: 'নারায়ণগঞ্জ', shohozCity: 'NARAYANGANJ', division: 'Dhaka', isHub: false },
  { code: 'KSG',  nameEn: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ', shohozCity: 'KISHOREGANJ', division: 'Dhaka', isHub: false },
  { code: 'MYM',  nameEn: 'Mymensingh', nameBn: 'ময়মনসিংহ', shohozCity: 'MYMENSINGH', division: 'Mymensingh', isHub: false },
  { code: 'JMP',  nameEn: 'Jamalpur', nameBn: 'জামালপুর', shohozCity: 'JAMALPUR', division: 'Mymensingh', isHub: false },
  { code: 'TGL',  nameEn: 'Tangail', nameBn: 'টাঙ্গাইল', shohozCity: 'TANGAIL', division: 'Dhaka', isHub: false },
  { code: 'SJG',  nameEn: 'Sirajganj', nameBn: 'সিরাজগঞ্জ', shohozCity: 'SIRAJGANJ', division: 'Rajshahi', isHub: false },
  { code: 'CTG',  nameEn: 'Chattogram', nameBn: 'চট্টগ্রাম', shohozCity: 'CHATTOGRAM', division: 'Chittagong', isHub: true },
  { code: 'COM',  nameEn: 'Comilla', nameBn: 'কুমিল্লা', shohozCity: 'COMILLA', division: 'Chittagong', isHub: false },
  { code: 'AKH',  nameEn: 'Akhaura', nameBn: 'আখাউড়া', shohozCity: 'AKHAURA', division: 'Chittagong', isHub: false },
  { code: 'LKS',  nameEn: 'Laksam', nameBn: 'লাকসাম', shohozCity: 'LAKSAM', division: 'Chittagong', isHub: false },
  { code: 'NOA',  nameEn: 'Noakhali', nameBn: 'নোয়াখালী', shohozCity: 'NOAKHALI', division: 'Chittagong', isHub: false },
  { code: 'CDP',  nameEn: 'Chandpur', nameBn: 'চাঁদপুর', shohozCity: 'CHANDPUR', division: 'Chittagong', isHub: false },
  { code: 'CXBZ', nameEn: "Cox's Bazar", nameBn: 'কক্সবাজার', shohozCity: "COX'S BAZAR", division: 'Chittagong', isHub: false },
  { code: 'SYT',  nameEn: 'Sylhet', nameBn: 'সিলেট', shohozCity: 'SYLHET', division: 'Sylhet', isHub: true },
  { code: 'SRM',  nameEn: 'Sreemangal', nameBn: 'শ্রীমঙ্গল', shohozCity: 'SREEMANGAL', division: 'Sylhet', isHub: false },
  { code: 'RAJ',  nameEn: 'Rajshahi', nameBn: 'রাজশাহী', shohozCity: 'RAJSHAHI', division: 'Rajshahi', isHub: false },
  { code: 'NTR',  nameEn: 'Natore', nameBn: 'নাটোর', shohozCity: 'NATORE', division: 'Rajshahi', isHub: false },
  { code: 'IWD',  nameEn: 'Ishwardi', nameBn: 'ঈশ্বরদী', shohozCity: 'ISHWARDI', division: 'Rajshahi', isHub: true },
  { code: 'STH',  nameEn: 'Santahar', nameBn: 'সান্তাহার', shohozCity: 'SANTAHAR', division: 'Rajshahi', isHub: false },
  { code: 'BOG',  nameEn: 'Bogura', nameBn: 'বগুড়া', shohozCity: 'BOGURA', division: 'Rajshahi', isHub: false },
  { code: 'CPN',  nameEn: 'Chapai Nawabganj', nameBn: 'চাঁপাইনবাবগঞ্জ', shohozCity: 'CHAPAINAWABGANJ', division: 'Rajshahi', isHub: false },
  { code: 'PBP',  nameEn: 'Parbatipur', nameBn: 'পার্বতীপুর', shohozCity: 'PARBATIPUR', division: 'Rangpur', isHub: true },
  { code: 'DNJ',  nameEn: 'Dinajpur', nameBn: 'দিনাজপুর', shohozCity: 'DINAJPUR', division: 'Rangpur', isHub: false },
  { code: 'RNG',  nameEn: 'Rangpur', nameBn: 'রংপুর', shohozCity: 'RANGPUR', division: 'Rangpur', isHub: false },
  { code: 'LMH',  nameEn: 'Lalmonirhat', nameBn: 'লালমনিরহাট', shohozCity: 'LALMONIRHAT', division: 'Rangpur', isHub: true },
  { code: 'PCG',  nameEn: 'Panchagarh', nameBn: 'পঞ্চগড়', shohozCity: 'PANCHAGARH', division: 'Rangpur', isHub: false },
  { code: 'KRG',  nameEn: 'Kurigram', nameBn: 'কুড়িগ্রাম', shohozCity: 'KURIGRAM', division: 'Rangpur', isHub: false },
  { code: 'CLH',  nameEn: 'Chilahati', nameBn: 'চিলাহাটি', shohozCity: 'CHILAHATI', division: 'Rangpur', isHub: false },
  { code: 'BMR',  nameEn: 'Burimari', nameBn: 'বুড়িমারী', shohozCity: 'BURIMARI', division: 'Rangpur', isHub: false },
  { code: 'KHU',  nameEn: 'Khulna', nameBn: 'খুলনা', shohozCity: 'KHULNA', division: 'Khulna', isHub: true },
  { code: 'JS',   nameEn: 'Jessore (Jashore)', nameBn: 'যশোর', shohozCity: 'JASHORE', division: 'Khulna', isHub: false },
  { code: 'BNP',  nameEn: 'Benapole', nameBn: 'বেনাপোল', shohozCity: 'BENAPOLE', division: 'Khulna', isHub: false },
];

// ─── Train metadata ───────────────────────────────────────────────────────────

export const TRAINS: TrainMeta[] = [
  { number: 1,   name: 'Chandpur Eid Special',    type: 'special',   confidenceGroup: 'g5' },
  { number: 3,   name: 'Tista Eid Special',        type: 'special',   confidenceGroup: 'g5' },
  { number: 4,   name: 'Tista Eid Special',        type: 'special',   confidenceGroup: 'g5' },
  { number: 9,   name: 'Parbatipur Eid Special',   type: 'special',   confidenceGroup: 'g5' },
  { number: 10,  name: 'Parbatipur Eid Special',   type: 'special',   confidenceGroup: 'g5' },
  { number: 41,  name: 'Kanchon Commuter',         type: 'commuter',  confidenceGroup: 'g5' },
  { number: 42,  name: 'Kanchon Commuter',         type: 'commuter',  confidenceGroup: 'g5' },
  { number: 57,  name: 'Rajshahi Commuter',        type: 'commuter',  confidenceGroup: 'g5' },
  { number: 58,  name: 'Rajshahi Commuter',        type: 'commuter',  confidenceGroup: 'g5' },
  { number: 77,  name: 'Rajshahi Commuter',        type: 'commuter',  confidenceGroup: 'g5' },
  { number: 78,  name: 'Rajshahi Commuter',        type: 'commuter',  confidenceGroup: 'g5' },
  { number: 109, name: 'Chapainawabganj Shuttle',  type: 'commuter',  confidenceGroup: 'g5' },
  { number: 110, name: 'Chapainawabganj Shuttle',  type: 'commuter',  confidenceGroup: 'g5' },
  { number: 701, name: 'Suborno Express',          type: 'intercity', confidenceGroup: 'g1' },
  { number: 702, name: 'Suborno Express',          type: 'intercity', confidenceGroup: 'g2' },
  { number: 703, name: 'Mahanagar Godhuli',        type: 'intercity', confidenceGroup: 'g1' },
  { number: 704, name: 'Mahanagar Provati',        type: 'intercity', confidenceGroup: 'g1' },
  { number: 705, name: 'Ekota Express',            type: 'intercity', confidenceGroup: 'g3' },
  { number: 706, name: 'Ekota Express',            type: 'intercity', confidenceGroup: 'g3' },
  { number: 707, name: 'Tista Express',            type: 'intercity', confidenceGroup: 'g1' },
  { number: 708, name: 'Tista Express',            type: 'intercity', confidenceGroup: 'g3' },
  { number: 709, name: 'Parabat Express',          type: 'intercity', confidenceGroup: 'g2' },
  { number: 710, name: 'Parabat Express',          type: 'intercity', confidenceGroup: 'g2' },
  { number: 711, name: 'Upakul Express',           type: 'intercity', confidenceGroup: 'g3' },
  { number: 712, name: 'Upakul Express',           type: 'intercity', confidenceGroup: 'g3' },
  { number: 713, name: 'Korotoa Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 714, name: 'Korotoa Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 715, name: 'Kapotaksha Express',       type: 'intercity', confidenceGroup: 'g4' },
  { number: 716, name: 'Kapotaksha Express',       type: 'intercity', confidenceGroup: 'g4' },
  { number: 717, name: 'Jayantika Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 718, name: 'Jayantika Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 719, name: 'Paharika Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 720, name: 'Paharika Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 721, name: 'Mohanagar Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 722, name: 'Mohanagar Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 723, name: 'Udayan Express',           type: 'intercity', confidenceGroup: 'g2' },
  { number: 724, name: 'Udayan Express',           type: 'intercity', confidenceGroup: 'g2' },
  { number: 725, name: 'Sundarban Express',        type: 'intercity', confidenceGroup: 'g1' },
  { number: 726, name: 'Sundarban Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 727, name: 'Rupsha Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 728, name: 'Rupsha Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 729, name: 'Meghna Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 730, name: 'Meghna Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 731, name: 'Barendra Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 732, name: 'Barendra Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 733, name: 'Titumir Express',          type: 'intercity', confidenceGroup: 'g2' },
  { number: 734, name: 'Titumir Express',          type: 'intercity', confidenceGroup: 'g2' },
  { number: 735, name: 'Aghnibina Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 736, name: 'Aghnibina Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 737, name: 'Egarosindhur Provati',     type: 'intercity', confidenceGroup: 'g5' },
  { number: 738, name: 'Egarosindhur Provati',     type: 'intercity', confidenceGroup: 'g5' },
  { number: 739, name: 'Upaban Express',           type: 'intercity', confidenceGroup: 'g1' },
  { number: 740, name: 'Upaban Express',           type: 'intercity', confidenceGroup: 'g3' },
  { number: 741, name: 'Turna',                    type: 'intercity', confidenceGroup: 'g4' },
  { number: 742, name: 'Turna',                    type: 'intercity', confidenceGroup: 'g4' },
  { number: 743, name: 'Brahmaputra Express',      type: 'intercity', confidenceGroup: 'g3' },
  { number: 744, name: 'Brahmaputra Express',      type: 'intercity', confidenceGroup: 'g3' },
  { number: 745, name: 'Jamuna Express',           type: 'intercity', confidenceGroup: 'g3' },
  { number: 746, name: 'Jamuna Express',           type: 'intercity', confidenceGroup: 'g3' },
  { number: 747, name: 'Simanta Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 748, name: 'Simanta Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 749, name: 'Egarosindhur Godhuli',     type: 'intercity', confidenceGroup: 'g5' },
  { number: 750, name: 'Egarosindhur Godhuli',     type: 'intercity', confidenceGroup: 'g5' },
  { number: 751, name: 'Lalmoni Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 752, name: 'Lalmoni Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 753, name: 'Silkcity Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 754, name: 'Silkcity Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 755, name: 'Madhumati Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 756, name: 'Madhumati Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 757, name: 'Drutojan Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 758, name: 'Drutojan Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 759, name: 'Padma Express',            type: 'intercity', confidenceGroup: 'g2' },
  { number: 760, name: 'Padma Express',            type: 'intercity', confidenceGroup: 'g2' },
  { number: 761, name: 'Sagardari Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 762, name: 'Sagardari Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 763, name: 'Chitra Express',           type: 'intercity', confidenceGroup: 'g2' },
  { number: 764, name: 'Chitra Express',           type: 'intercity', confidenceGroup: 'g2' },
  { number: 765, name: 'Nilsagar Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 766, name: 'Nilsagar Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 767, name: 'Dolonchapa Express',       type: 'intercity', confidenceGroup: 'g5' },
  { number: 768, name: 'Dolonchapa Express',       type: 'intercity', confidenceGroup: 'g5' },
  { number: 769, name: 'Dhumketu Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 770, name: 'Dhumketu Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 771, name: 'Rangpur Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 772, name: 'Rangpur Express',          type: 'intercity', confidenceGroup: 'g3' },
  { number: 773, name: 'Kalni Express',            type: 'intercity', confidenceGroup: 'g4' },
  { number: 774, name: 'Kalni Express',            type: 'intercity', confidenceGroup: 'g4' },
  { number: 775, name: 'Sirajganj Express',        type: 'intercity', confidenceGroup: 'g3' },
  { number: 776, name: 'Sirajganj Express',        type: 'intercity', confidenceGroup: 'g3' },
  { number: 777, name: 'Hawr Express',             type: 'intercity', confidenceGroup: 'g4' },
  { number: 778, name: 'Hawr Express',             type: 'intercity', confidenceGroup: 'g4' },
  { number: 779, name: 'Dhalarchar Express',       type: 'intercity', confidenceGroup: 'g4' },
  { number: 780, name: 'Dhalarchar Express',       type: 'intercity', confidenceGroup: 'g4' },
  { number: 781, name: 'Kishoreganj Express',      type: 'intercity', confidenceGroup: 'g5' },
  { number: 782, name: 'Kishoreganj Express',      type: 'intercity', confidenceGroup: 'g5' },
  { number: 783, name: 'Tungipara Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 784, name: 'Tungipara Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 785, name: 'Bijoy Express',            type: 'intercity', confidenceGroup: 'g4' },
  { number: 786, name: 'Bijoy Express',            type: 'intercity', confidenceGroup: 'g4' },
  { number: 787, name: 'Sonar Bangla Express',     type: 'intercity', confidenceGroup: 'g1' },
  { number: 788, name: 'Sonar Bangla Express',     type: 'intercity', confidenceGroup: 'g1' },
  { number: 789, name: 'Mohonganj Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 790, name: 'Mohonganj Express',        type: 'intercity', confidenceGroup: 'g4' },
  { number: 791, name: 'Banalata Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 792, name: 'Banalata Express',         type: 'intercity', confidenceGroup: 'g2' },
  { number: 793, name: 'Panchagarh Express',       type: 'intercity', confidenceGroup: 'g3' },
  { number: 794, name: 'Panchagarh Express',       type: 'intercity', confidenceGroup: 'g3' },
  { number: 795, name: 'Benapole Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 796, name: 'Benapole Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 797, name: 'Kurigram Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 798, name: 'Kurigram Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 799, name: 'Jamalpur Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 800, name: 'Jamalpur Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 801, name: 'Chattala Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 802, name: 'Chattala Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 803, name: 'Banglabandha Express',     type: 'intercity', confidenceGroup: 'g3' },
  { number: 804, name: 'Banglabandha Express',     type: 'intercity', confidenceGroup: 'g3' },
  { number: 805, name: 'Chilahati Express',        type: 'intercity', confidenceGroup: 'g3' },
  { number: 806, name: 'Chilahati Express',        type: 'intercity', confidenceGroup: 'g3' },
  { number: 809, name: 'Burimari Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 810, name: 'Burimari Express',         type: 'intercity', confidenceGroup: 'g3' },
  { number: 813, name: "Cox's Bazar Express",      type: 'intercity', confidenceGroup: 'g3' },
  { number: 814, name: "Cox's Bazar Express",      type: 'intercity', confidenceGroup: 'g3' },
  { number: 815, name: 'Parjotak Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 816, name: 'Parjotak Express',         type: 'intercity', confidenceGroup: 'g4' },
  { number: 821, name: 'Shaikat Express',          type: 'intercity', confidenceGroup: 'g4' },
  { number: 822, name: 'Probal Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 823, name: 'Probal Express',           type: 'intercity', confidenceGroup: 'g4' },
  { number: 824, name: 'Shaikat Express',          type: 'intercity', confidenceGroup: 'g4' },
  { number: 825, name: 'Jahanabad Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 826, name: 'Jahanabad Express',        type: 'intercity', confidenceGroup: 'g2' },
  { number: 827, name: 'Ruposhi Bangla Express',   type: 'intercity', confidenceGroup: 'g4' },
  { number: 828, name: 'Ruposhi Bangla Express',   type: 'intercity', confidenceGroup: 'g4' },
];

// ─── Stop sequences (station codes per train) ─────────────────────────────────
// Key: train number → ordered array of station codes the train serves
// This encodes topology only — NOT departure/arrival times.

export const STOP_SEQUENCES: Record<number, string[]> = {
  1:   ['DHKA','CDP'],
  3:   ['DHKA','RNG'],      4:   ['RNG','DHKA'],
  9:   ['DHKA','PBP'],      10:  ['PBP','DHKA'],
  41:  ['DHKA','NRG'],      42:  ['NRG','DHKA'],
  57:  ['RAJ','IWD'],       58:  ['IWD','RAJ'],
  77:  ['RAJ','IWD'],       78:  ['IWD','RAJ'],
  109: ['RAJ','CPN'],       110: ['CPN','RAJ'],
  701: ['DHKA','DABB','NSD','COM','CTG'],
  702: ['CTG','COM','NSD','DHKA'],
  703: ['CTG','COM','AKH','BBZ','NSD','DHKA'],
  704: ['DHKA','NSD','BBZ','AKH','COM','CTG'],
  705: ['DHKA','IWD','STH','PBP'],
  706: ['PBP','STH','IWD','DHKA'],
  707: ['DHKA','DABB','TNG','IWD','STH','BOG','PBP','LMH'],
  708: ['LMH','PBP','BOG','STH','IWD','TNG','DABB','DHKA'],
  709: ['DHKA','DABB','BBZ','AKH','SRM','SYT'],
  710: ['SYT','SRM','AKH','BBZ','DABB','DHKA'],
  711: ['DHKA','COM','LKS','NOA'],
  712: ['NOA','LKS','COM','DHKA'],
  713: ['DHKA','IWD','STH','PBP','LMH'],
  714: ['LMH','PBP','STH','IWD','DHKA'],
  715: ['DHKA','IWD','JS','KHU'],
  716: ['KHU','JS','IWD','DHKA'],
  717: ['DHKA','DABB','BBZ','AKH','SRM','SYT'],
  718: ['SYT','SRM','AKH','BBZ','DABB','DHKA'],
  719: ['DHKA','BBZ','AKH','SRM','SYT'],
  720: ['SYT','SRM','AKH','BBZ','DHKA'],
  721: ['DHKA','JDP','TGL','IWD','NTR','RAJ'],
  722: ['RAJ','NTR','IWD','TGL','JDP','DHKA'],
  723: ['DHKA','BBZ','AKH','SRM','SYT'],
  724: ['SYT','SRM','AKH','BBZ','DHKA'],
  725: ['DHKA','DABB','TNG','IWD','JS','KHU'],
  726: ['KHU','JS','IWD','TNG','DABB','DHKA'],
  727: ['DHKA','IWD','JS','KHU'],
  728: ['KHU','JS','IWD','DHKA'],
  729: ['DHKA','COM','CTG'],    730: ['CTG','COM','DHKA'],
  731: ['DHKA','IWD','RAJ','CPN'],
  732: ['CPN','RAJ','IWD','DHKA'],
  733: ['DHKA','IWD','NTR','RAJ'],
  734: ['RAJ','NTR','IWD','DHKA'],
  735: ['DHKA','BBZ','AKH','SRM','SYT'],
  736: ['SYT','SRM','AKH','BBZ','DHKA'],
  737: ['DHKA','KSG'],          738: ['KSG','DHKA'],
  739: ['DHKA','DABB','BBZ','AKH','SRM','SYT'],
  740: ['SYT','SRM','AKH','BBZ','DABB','DHKA'],
  741: ['DHKA','COM','CTG'],    742: ['CTG','COM','DHKA'],
  743: ['DHKA','MYM','JMP'],    744: ['JMP','MYM','DHKA'],
  745: ['DHKA','MYM','JMP'],    746: ['JMP','MYM','DHKA'],
  747: ['DHKA','IWD','STH','PBP','CLH'],
  748: ['CLH','PBP','STH','IWD','DHKA'],
  749: ['DHKA','KSG'],          750: ['KSG','DHKA'],
  751: ['DHKA','IWD','STH','PBP','LMH'],
  752: ['LMH','PBP','STH','IWD','DHKA'],
  753: ['DHKA','JDP','TGL','IWD','NTR','RAJ'],
  754: ['RAJ','NTR','IWD','TGL','JDP','DHKA'],
  755: ['DHKA','IWD','JS','KHU'],
  756: ['KHU','JS','IWD','DHKA'],
  757: ['DHKA','IWD','JS','KHU'],
  758: ['KHU','JS','IWD','DHKA'],
  759: ['DHKA','IWD','NTR','RAJ'],
  760: ['RAJ','NTR','IWD','DHKA'],
  761: ['DHKA','IWD','JS','KHU'],
  762: ['KHU','JS','IWD','DHKA'],
  763: ['DHKA','IWD','JS','KHU'],
  764: ['KHU','JS','IWD','DHKA'],
  765: ['DHKA','IWD','STH','PBP','CLH'],
  766: ['CLH','PBP','STH','IWD','DHKA'],
  767: ['DHKA','MYM'],          768: ['MYM','DHKA'],
  769: ['DHKA','JDP','TGL','IWD','NTR','RAJ'],
  770: ['RAJ','NTR','IWD','TGL','JDP','DHKA'],
  771: ['DHKA','IWD','STH','PBP','RNG'],
  772: ['RNG','PBP','STH','IWD','DHKA'],
  773: ['DHKA','NSD','BBZ'],    774: ['BBZ','NSD','DHKA'],
  775: ['DHKA','SJG'],          776: ['SJG','DHKA'],
  777: ['DHKA','NSD','BBZ'],    778: ['BBZ','NSD','DHKA'],
  779: ['RAJ','CPN'],           780: ['CPN','RAJ'],
  781: ['DHKA','KSG'],          782: ['KSG','DHKA'],
  783: ['DHKA','IWD','JS','KHU'],
  784: ['KHU','JS','IWD','DHKA'],
  785: ['DHKA','IWD','JS','KHU'],
  786: ['KHU','JS','IWD','DHKA'],
  787: ['DHKA','DABB','CTG'],   788: ['CTG','DABB','DHKA'],
  789: ['DHKA','NSD','BBZ'],    790: ['BBZ','NSD','DHKA'],
  791: ['DHKA','IWD','RAJ'],    792: ['RAJ','IWD','DHKA'],
  793: ['DHKA','IWD','STH','DNJ','PCG'],
  794: ['PCG','DNJ','STH','IWD','DHKA'],
  795: ['DHKA','IWD','JS','BNP'],
  796: ['BNP','JS','IWD','DHKA'],
  797: ['DHKA','IWD','STH','PBP','KRG'],
  798: ['KRG','PBP','STH','IWD','DHKA'],
  799: ['DHKA','MYM','JMP'],    800: ['JMP','MYM','DHKA'],
  801: ['DHKA','COM','CTG'],    802: ['CTG','COM','DHKA'],
  803: ['DHKA','IWD','STH','DNJ','PCG'],
  804: ['PCG','DNJ','STH','IWD','DHKA'],
  805: ['DHKA','IWD','STH','PBP','CLH'],
  806: ['CLH','PBP','STH','IWD','DHKA'],
  809: ['DHKA','IWD','STH','PBP','BMR'],
  810: ['BMR','PBP','STH','IWD','DHKA'],
  813: ['DHKA','COM','CTG','CXBZ'],
  814: ['CXBZ','CTG','COM','DHKA'],
  815: ['DHKA','COM','CTG'],    816: ['CTG','COM','DHKA'],
  821: ['DHKA','COM','CTG'],    822: ['DHKA','COM','CTG'],
  823: ['CTG','COM','DHKA'],    824: ['CTG','COM','DHKA'],
  825: ['DHKA','KHU'],          826: ['KHU','DHKA'],
  827: ['DHKA','COM','CTG'],    828: ['CTG','COM','DHKA'],
};
